Fixed the position of the pointer in error messages for strings with a non-closed end delimiter.
Example:

	say "missing end delimiter

Fails with message:

File : y.sf
Line : 1 : 4
Error: can't find the quoted string terminator <<">>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
say "missing end delimiter
    ^
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~